name: Android Push Validation

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Prepare Secret Files   
        run: |   
           echo "${{ secrets.SIGN_KEYSTORE }}" > vault-release.jks.asc   
           gpg -d --passphrase "${{ secrets.SIGN_KEYSTORE_PASSWORD }}" --batch vault-release.jks.asc > vault-release.jks   
           echo "${{ secrets.SIGN_KEYSTORE_PROPERTIES }}" > keystore.properties.asc   
           gpg -d --passphrase "${{ secrets.SIGN_KEYSTORE_PROPERTIES_PASSWORD }}" --batch keystore.properties.asc > keystore.properties
      - name: Build with Gradle and create APK
        run: ./gradlew build assembleDebug
      - name: Upload APK
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.FTP_RELEASE_HOST }}
          port: ${{ secrets.FTP_RELEASE_PORT }}
          username: ${{ secrets.FTP_RELEASE_USER }}
          ssh_private_key: ${{ secrets.FTP_RELEASE_KEY }}
          remote_path: ${{ secrets.FTP_RELEASE_SERVER_DIR }}
          local_path: app/build/outputs/apk/
