name: Android Push Validation

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and create APK
        run: ./gradlew build assembleDebug
      - name: Upload APK
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_RELEASE_HOST }}
          username: ${{ secrets.FTP_RELEASE_USER }}
          password: ${{ secrets.FTP_RELEASE_PASSWORD }}
          server-dir: ${{ secrets.FTP_RELEASE_SERVER_DIR }}
          local-dir: app/build/outputs/apk/
