name: SonarQube
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Sonaqube Scan with Gradle
      env:
        HOST: ${{ secrets.SONARQUBE_HOST }}
        TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      run: ./gradlew sonarqube -Dsonar.host.url="$HOST" -Dsonar.login="$TOKEN"
      
